[build]
  command = "npm run build"
  publish = ".next"

[context.production]
  publish = ".next"
  command = "npm run build"

[context.deploy-preview]
  publish = ".next"
  command = "npm run build"

[context.branch-deploy]
  publish = ".next"
  command = "npm run build"
